---
  - hosts: k8sworker
    remote_user: root
    roles:
      - container_network_routes 


    environment:
      http_proxy: http://10.144.106.132:8678
      https_proxy: http://10.144.106.132:8678
